/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import models.DBManager;
import models.Staff;
import models.Product;

/**
 *
 * @author mark
 */
public class StaffEditProducts extends javax.swing.JFrame {
    
    private Staff loggedInStaff;
    private Product productToDelete;
    private HashMap<Integer, Product> products;

    /**
     * Creates new form StaffEditProducts
     */
    public StaffEditProducts(Staff staff) {
        loggedInStaff = staff; //sets the Staff object "loggedInStaff" to staff
        DBManager db  = new DBManager(); //loads a new instance of Database Manager
        //sets the products HashMap to populate with the 
        //contents from "loadProducts"
        products = db.loadProducts(); 
        initComponents();
        
        this.getContentPane().setBackground(Color.lightGray); //set colour to light grey
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffBackHome = new javax.swing.JButton();
        lblCatagories = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCatagories = new javax.swing.JList<>();
        lblEditProducts = new javax.swing.JLabel();
        lblProducts = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList<>();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        staffBackHome.setText("RETURN TO STAFF HOME");
        staffBackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffBackHomeActionPerformed(evt);
            }
        });

        lblCatagories.setText("CATAGORIES");

        listCatagories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clothing", "Footwear" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCatagories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCatagoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCatagories);

        lblEditProducts.setText("EDIT PRODUCTS");

        lblProducts.setText("PRODUCTS");

        listProducts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProductsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listProducts);

        btnEditProduct.setText("Edit Product");
        btnEditProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProductActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(lblCatagories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(staffBackHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteProduct))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEditProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffBackHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCatagories)
                    .addComponent(lblProducts))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditProduct)
                        .addComponent(btnDeleteProduct))
                    .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffBackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffBackHomeActionPerformed
        //returns back to "Staff Home" menu
        StaffHome smenu = new StaffHome(loggedInStaff);
        this.dispose();
        smenu.setVisible(true);
    }//GEN-LAST:event_staffBackHomeActionPerformed

    private void listCatagoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCatagoriesValueChanged
        //new instance of DefaultListModel
        DefaultListModel productList = new DefaultListModel(); 
        
        //get and store the selected value from the list, will be either
        //clothing or footwear
        String selectedCategory = listCatagories.getSelectedValue(); 
        
        //returns a view of the mappings in the productEntry map
        for(Map.Entry<Integer, Product> productEntry : products.entrySet())
        {
            //get and store products from the productEntry map
            Product product = productEntry.getValue();

            //if the product class is the same as the "footwear" or "clothing"
            //class in models, add the element to the DefaultListModel
            if (product.getClass().getName().equals("models." + selectedCategory))
            {
                productList.addElement(product);
            }
        }


        listProducts.setModel(productList);
    }//GEN-LAST:event_listCatagoriesValueChanged

    private void listProductsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProductsValueChanged
        Object selectedProduct = listProducts.getSelectedValue();
       
        
    }//GEN-LAST:event_listProductsValueChanged

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        if (listProducts.getSelectedIndex() == -1){
            lblErrorMessage.setText("Error - Please select a product.");
        }

        else{
            //casting the selected product in to a "Product" object
            Object selectedProductObject = (Object)listProducts.getSelectedValue();
            Product selectedProduct = (Product)selectedProductObject;

            EditProducts editProducts = new EditProducts(loggedInStaff, selectedProduct);
            this.dispose();
            editProducts.setVisible(true);
        }
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        if (listProducts.getSelectedIndex() == -1){
            lblErrorMessage.setText("Error - Please select a product.");
        }

        else{
            //casting the selected product in to a "Product" object
            Object selectedProductObject = (Object)listProducts.getSelectedValue();
            Product selectedProduct = (Product)selectedProductObject;

            DBManager db = new DBManager();
            //delete the selected product using its product id

            int result = JOptionPane.showConfirmDialog(null, "Are you sure?");

            if (result == (JOptionPane.YES_OPTION))
            {
                db.deleteProduct(selectedProduct.getProductId());

                //remove the deleted product from the JList as it is no longer in the database
                lblErrorMessage.setText("Product: " + selectedProduct.getProductName() + " deleted.");
                ((DefaultListModel) listProducts.getModel()).remove(listProducts.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffEditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffEditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffEditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffEditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StaffEditProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCatagories;
    private javax.swing.JLabel lblEditProducts;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblProducts;
    private javax.swing.JList<String> listCatagories;
    private javax.swing.JList<String> listProducts;
    private javax.swing.JButton staffBackHome;
    // End of variables declaration//GEN-END:variables
}
